<?php
/* @var $block Studio3Marketing\Magento2Blog\Block\Index */

// Fetch all posts
$blogPosts = $block->fetchBlogIndexPosts();
$totalPosts = count($blogPosts['data']);
$limit = $block->getPostsPerPageLimit();

// Fetch the current page from the query string, default to 1 if not present
$currentPage = isset($_GET['page']) ? (int)$_GET['page'] : 1;
$offset = ($currentPage - 1) * $limit;

// Calculate total pages
$totalPages = ceil($totalPosts / $limit);

// Slice posts based on current page
$postsOnPage = array_slice($blogPosts['data'], $offset, $limit);

?>

    <H2>All Blog Posts</H2>

<?php
if (!empty($postsOnPage)) {
    foreach ($postsOnPage as $post) {
        $_articleLink = $block->getPostLink($post['id'], $post['attributes']['slug']);
        ?>
        <div class="blog-post">
            <?php if (!empty($post['attributes']['published_date'])): ?>
                <p class="published-date"><?= date("F j, Y", strtotime($post['attributes']['published_date'])) ?></p>
            <?php else: ?>
                <p class="published-date"><?= date("F j, Y", strtotime($post['meta']['published_date'])) ?></p>
            <?php endif; ?>
            <h2 class="blog-title"><?= htmlspecialchars($post['attributes']['title'] ?? '') ?></h2>
            <a class="blog-image" href="<?= $_articleLink ?>">
                <img src="https://www.datocms-assets.com<?= $post['attributes']['featured_image']['path'] ?>" alt="<?= htmlspecialchars($post['attributes']['featured_image']['alt'] ?? '') ?>">
            </a>
            <article>
                <?= htmlspecialchars(substr(strip_tags($post['attributes']['content'] ?? ''), 0, 200)) . "..." ?>
            </article>
            <a class="blog-link" href="<?= $_articleLink ?>">Read Now</a>
        </div>
        <?php
    }
} else {
    echo '<p>No blog posts found.</p>';
}
?>

<?php if ($totalPages > 1): // Only show pagination if there's more than one page ?>
    <div class="pagination">
        <?php if ($currentPage > 1): ?>
            <a class="previous-btn" href="?page=<?= $currentPage - 1 ?>">Previous</a>
        <?php endif; ?>

        <?php for ($i = 1; $i <= $totalPages; $i++): ?>
            <a href="?page=<?= $i ?>"<?= $i == $currentPage ? ' class="active"' : '' ?>><?= $i ?></a>
        <?php endfor; ?>

        <?php if ($currentPage < $totalPages): ?>
            <a class="next-btn" href="?page=<?= $currentPage + 1 ?>">Next</a>
        <?php endif; ?>
    </div>
<?php endif; ?>
